#Range: 5 ~ 5
maxRank = 5
#Range: 1 ~ 100
maxLevelPerRank = 4
#Range: 1 ~ 100
levelPerSubStat = 4
#Range: 64 ~ 1024
storageSmall = 256
#Range: 64 ~ 1024
storageLarge = 512
#Range: 1.0 ~ 10.0
expConsumptionRankFactor = 2.0
#Range: 1.0 ~ 10.0
expLevelFactor = 1.05
#Range: 1 ~ 10000
baseExpConsumption = 100
#Range: 0.0 ~ 1.0
expRetention = 0.9
#Range: 1 ~ 1000000
baseExpConversion = 100
#Range: 1.0 ~ 10.0
expConversionRankFactor = 2.0
#Min health requirement would still be effective
useLevelDropForHostility = true
#Stack multiplicatively with drop chance specified in datapack
#Range: 0.0 ~ 10.0
globalDropChanceMultiplier = 1.0
