enableEntitySpecificDatapack = true
enableStructureSpecificDatapack = true

[scaling]
	#Range: 0.0 ~ 1000.0
	healthFactor = 0.03
	exponentialHealth = false
	#Range: 0.0 ~ 1000.0
	damageFactor = 0.02
	exponentialDamage = false
	#Range: 0.0 ~ 1000.0
	expDropFactor = 0.05
	#Range: 0.0 ~ 1000.0
	drownedTridentChancePerLevel = 0.005
	#Range: 0 ~ 1000
	dimensionFactor = 10
	#Range: 0.0 ~ 1000.0
	distanceFactor = 0.003
	#Not applicable to mobs with minimum level.
	#Range: 0.0 ~ 1.0
	globalApplyChance = 1.0
	#Not applicable to mobs with minimum level.
	#Range: 0.0 ~ 1.0
	globalTraitChance = 1.0
	#Not applicable to mobs with minimum level.
	#Range: 0.0 ~ 1.0
	globalTraitSuppression = 0.1
	allowLegendary = true
	allowSectionDifficulty = true
	allowBypassMinimum = true
	allowExtraEnchantments = true
	#Range: 0 ~ 1000
	defaultLevelBase = 20
	#Range: 0.0 ~ 1000.0
	defaultLevelVar = 16.0
	#Range: 0.0 ~ 10.0
	defaultLevelScale = 1.5
	#Default k% = 0.01, so Lv.N mobs with have N% chance to have trait
	#Mobs with entity config and trait chance of 1 will not be affected
	#Range: 0.0 ~ 1.0
	initialTraitChanceSlope = 0.01
	#Range: 0.0 ~ 1.0
	splitDropRateFactor = 0.25
	allowNoAI = false
	allowPlayerAllies = false
	allowTraitOnOwnable = false
	#Range: 0.0 ~ 1.0
	dropRateFromSpawner = 0.5
	#Range: 0.0 ~ 1.0
	equipmentDropRate = 0.085

[difficulty]
	#Range: 100 ~ 100000
	maxPlayerLevel = 2000
	#Range: 100 ~ 100000
	maxMobLevel = 3000
	#Range: 1 ~ 100000
	killsPerLevel = 30
	#Range: 0.0 ~ 2.0
	playerDeathDecay = 0.8
	keepInventoryRuleKeepDifficulty = false
	deathDecayDimension = true
	deathDecayTraitCap = true
	#Range: 0 ~ 128
	newPlayerProtectRange = 48

[orb_and_spawner]
	allowHostilityOrb = true
	enableHostilityOrbDrop = true
	#0 means 1x1x1 section, 1 means 3x3x3 sections, 2 means 5x5x5 sections
	#Range: 0 ~ 10
	orbRadius = 2
	allowHostilitySpawner = true
	#Range: 1 ~ 64
	hostilitySpawnCount = 16
	#Range: 1 ~ 10000
	hostilitySpawnLevelFactor = 2

[items]
	banBottles = false
	disableHostilityLootCurioRequirement = false
	#Range: 0 ~ 1000
	bottleOfCurseLevel = 50
	#Range: 20 ~ 10000
	witchChargeMinDuration = 200
	#Range: 0.0 ~ 1.0
	ringOfLifeMaxDamage = 0.9
	#Range: 1 ~ 10000
	flameThornTime = 100
	#Range: 1 ~ 256
	ringOfReflectionRadius = 16
	#Range: 1 ~ 100
	witchWandFactor = 4
	#Range: 0.0 ~ 1.0
	ringOfCorrosionFactor = 0.2
	#Range: 0.0 ~ 1.0
	ringOfCorrosionPenalty = 0.1
	#Range: 0.0 ~ 1.0
	ringOfHealingRate = 0.05
	#Range: 0 ~ 1000
	envyExtraLevel = 50
	#Range: 0 ~ 1000
	greedExtraLevel = 50
	#Range: 0 ~ 1000
	lustExtraLevel = 50
	#Range: 0 ~ 1000
	wrathExtraLevel = 50
	#Range: 1.0 ~ 10.0
	greedDropFactor = 2.0
	#Range: 0.0 ~ 1.0
	envyDropRate = 0.02
	#Range: 0.0 ~ 1.0
	gluttonyBottleDropRate = 0.02
	#Range: 0.0 ~ 1.0
	wrathDamageBonus = 0.05
	#Range: 0.0 ~ 1.0
	prideDamageBonus = 0.02
	#Range: 0.0 ~ 1.0
	prideHealthBonus = 0.02
	#Range: 0.01 ~ 1.0
	prideTraitFactor = 0.5
	#Range: 0 ~ 1000
	abrahadabraExtraLevel = 100
	#Range: 0 ~ 1000
	nidhoggurExtraLevel = 100
	#Range: 0.0 ~ 10.0
	nidhoggurDropFactor = 0.01
	nidhoggurCapAtItemMaxStack = false
	bookOfReprintSpread = false
	#Range: 0.0 ~ 1.0
	insulatorFactor = 0.8

[performance]
	enableCurioCheckFilter = true
	#Range: 1 ~ 1000
	removeTraitCheckInterval = 10
	#Range: 1 ~ 1000
	auraEffectApplicationInterval = 5
	#Range: 1 ~ 1000
	selfEffectApplicationInterval = 200

[traits]
	#Range: 0.0 ~ 1000.0
	tankHealth = 0.5
	#Range: 0.0 ~ 1000.0
	tankArmor = 10.0
	#Range: 0.0 ~ 1000.0
	tankTough = 4.0
	#Range: 0.0 ~ 1000.0
	speedy = 0.2
	#Range: 0.0 ~ 1000.0
	regen = 0.02
	#Range: 0.0 ~ 1000.0
	adaptFactor = 0.5
	#Range: 0.0 ~ 1000.0
	reflectFactor = 0.3
	#Range: 1 ~ 60000
	dispellTime = 200
	#Range: 0 ~ 3000
	fieryTime = 5
	#Range: 0 ~ 3000
	weakTime = 200
	#Range: 0 ~ 3000
	slowTime = 200
	#Range: 0 ~ 3000
	poisonTime = 200
	#Range: 0 ~ 3000
	witherTime = 200
	#Range: 0 ~ 3000
	levitationTime = 200
	#Range: 0 ~ 3000
	blindTime = 200
	#Range: 0 ~ 3000
	confusionTime = 200
	#Range: 0 ~ 3000
	soulBurnerTime = 60
	#Range: 0 ~ 3000
	freezingTime = 200
	#Range: 0 ~ 3000
	curseTime = 200
	#Range: 0 ~ 3000
	teleportDuration = 100
	#Range: 0 ~ 64
	teleportRange = 16
	#Range: 0 ~ 64
	repellRange = 10
	#Range: 0.0 ~ 1.0
	repellStrength = 0.2
	#Range: 0.0 ~ 1.0
	corrosionDurability = 0.3
	#Range: 0.0 ~ 1.0
	corrosionDamage = 0.25
	#Range: 0.0 ~ 1.0
	erosionDurability = 0.1
	#Range: 0.0 ~ 1.0
	erosionDamage = 0.25
	#Range: 1 ~ 1000
	ragnarokTime = 20
	ragnarokSealBackpack = false
	ragnarokSealSlotAdder = false
	#Range: 1 ~ 10000
	killerAuraDamage = 10
	#Range: 1 ~ 32
	killerAuraRange = 6
	#Range: 1 ~ 10000
	killerAuraInterval = 120
	#Range: 1 ~ 10000
	shulkerInterval = 40
	#Range: 1 ~ 10000
	explodeShulkerInterval = 60
	#Range: 0.0 ~ 100.0
	drainDamage = 0.1
	#Range: 0.0 ~ 100.0
	drainDuration = 0.5
	#Range: 0 ~ 10000
	drainDurationMax = 1200
	#Range: 0 ~ 3000
	counterStrikeDuration = 100
	#Range: 0 ~ 64
	counterStrikeRange = 6
	#Range: 0 ~ 64
	pullingRange = 10
	#Range: 0.0 ~ 10.0
	pullingStrength = 0.2
	#Range: 0.0 ~ 1.0
	reprintDamage = 0.02
	#Range: 0 ~ 10000
	reprintBypass = 10
	#Range: 0 ~ 100
	gravityRange = 10
	#Range: 0 ~ 100
	moonwalkRange = 10
	#Range: 0 ~ 100
	arenaRange = 24

[toggle]
	allow_tank = true
	allow_speedy = true
	allow_protection = true
	allow_invisible = true
	allow_fiery = true
	allow_regenerate = true
	allow_adaptive = true
	allow_reflect = true
	allow_shulker = true
	allow_grenade = true
	allow_corrosion = true
	allow_erosion = true
	allow_growth = true
	allow_split = true
	allow_drain = true
	allow_counter_strike = true
	allow_gravity = true
	allow_moonwalk = true
	allow_arena = true
	allow_dementor = true
	allow_dispell = true
	allow_undying = true
	allow_teleport = true
	allow_repelling = true
	allow_pulling = true
	allow_reprint = true
	allow_killer_aura = true
	allow_ragnarok = true
	allow_master = true
	allow_weakness = true
	allow_slowness = true
	allow_poison = true
	allow_wither = true
	allow_levitation = true
	allow_blindness = true
	allow_nausea = true
	allow_soul_burner = true
	allow_freezing = true
	allow_cursed = true
