showTraitOverHead = true
showLevelOverHead = true
#Range: 0 ~ 128
overHeadRenderDistance = 32
#Range: -100.0 ~ 100.0
overHeadRenderOffset = 0.0
overHeadRenderFullBright = true
#Range: > -2147483648
overHeadLevelColor = 11184810
#Range: > -2147483648
overHeadLevelColorAbyss = 16733525
showOnlyWhenHovered = false
#Range: 1 ~ 256
glowingRangeHidden = 32
#Range: 1 ~ 256
glowingRangeNear = 16
showUndyingParticles = true
