[general]
	barehandRetrieve = true
	#Make mobs aggro to iron golem automatically aggro to modular golems
	doEnemyAggro = true
	allowDimensionChange = false
	#Range: 1 ~ 1000
	summonDistance = 64
	#Range: 1 ~ 1000
	retrieveDistance = 64
	#Range: 1 ~ 1000
	retrieveRange = 20
	ownerPickupOnly = true
	#When enabled, the following features will be disabled when player holds item in hand:
	#- give item to golem or take items from golem by right click
	#- order dog golem to seat
	strictInteract = false
	allowEditCuriosForOthers = true
	#Max golem activity radius before following player in follow mode
	#Range: 1.0 ~ 100.0
	startFollowRadius = 10.0
	#Max golem activity radius before willing to go back to origin in wander mode
	#Range: 1.0 ~ 100.0
	stopWanderRadius = 20.0
	#Range: 1.0 ~ 100.0
	maxWanderRadius = 30.0
	#Range: 0.0 ~ 2.0
	riddenSpeedFactor = 0.8
	#Range: 1 ~ 10000
	targetResetTime = 600
	#Range: 0.0 ~ 10.0
	targetResetNoMovementRange = 0.5
	#Range: 0 ~ 100
	largeGolemSlot = 4
	#Range: 0 ~ 100
	humanoidGolemSlot = 3
	#Range: 0 ~ 100
	dogGolemSlot = 2

[modifiers]
	#Range: 0.0 ~ 100.0
	thorn = 0.2
	#Range: 0.0 ~ 1.0
	magicResistance = 0.2
	#Range: 0.0 ~ 1.0
	explosionResistance = 0.2
	#Range: 0.0 ~ 1.0
	damageCap = 0.1
	#Range: 1 ~ 10000
	thunderHeal = 10
	#Range: 1 ~ 16
	basePickupRange = 6
	#Range: 1 ~ 10000
	mendingXpCost = 2

[twilightforest]
	#Range: 0.0 ~ 100.0
	fiery = 0.5
	#Range: 0.0 ~ 100.0
	compatTFHealing = 0.5
	#Range: 0.0 ~ 100.0
	compatTFDamage = 0.2
	#Range: 1 ~ 100000
	carminiteTime = 20

[botania]
	#Range: 1 ~ 50000
	mendingManaCost = 200
	#Range: 0.1 ~ 100.0
	manaMendingVal = 4.0
	#Range: 0.0 ~ 100.0
	manaBoostingDamage = 0.2
	#Range: 0 ~ 100000
	manaBoostingCost = 500
	#Range: 0 ~ 100000
	manaProductionVal = 20
	#Range: 0.0 ~ 1.0
	manaBurstDamage = 0.25
	#Range: 0 ~ 100000
	manaBurstCost = 2000
	#Range: 0.0 ~ 1.0
	pixieAttackProb = 0.05
	#Range: 0.0 ~ 1.0
	pixiecounterattackProb = 0.25

[create]
	#Range: 0.0 ~ 10000.0
	coating = 1.0
	#Range: 0.0 ~ 1.0
	mechSpeed = 0.2
	#Range: 0.0 ~ 1.0
	mechAttack = 0.2
	#Range: 1 ~ 364
	mechMaxFuel = 3

[l2complements]
	#Range: 0 ~ 10000
	conduitCooldown = 120
	#Range: 0 ~ 10000
	conduitDamage = 2
	#Range: 0.0 ~ 100.0
	conduitBoostAttack = 0.2
	#Range: 0 ~ 100
	conduitBoostArmor = 5
	#Range: 0 ~ 100
	conduitBoostToughness = 2
	#Range: 0.0 ~ 100.0
	conduitBoostSpeed = 0.2
	#Range: 0.0 ~ 100.0
	conduitBoostReduction = 0.2
	#Range: 1 ~ 32
	teleportRadius = 6
	#Range: 1 ~ 10000
	teleportCooldown = 40
	#Range: 0.0 ~ 100.0
	targetDamageBonus = 0.5
