#Only apply half the sweeping damage to indirectly hit mobs for better balancing of the sweeping feature.
#Default Value: true
#Requires Restart: Game
halve_sweeping_damage = true
#Increase snowball and egg stack size from 16 to 64, and potion stack size from 1 to 16 (only for potions of the same type of course).
#Default Value: true
#Requires Restart: Game
increase_stack_size = true

[attributes]
	#Makes it so that swords, hoes, and tridents have an increased reach when attacking.
	#Default Value: true
	#Requires Restart: Game
	additional_entity_interaction_range = true
	#Overrides for setting and balancing attack speed values of items.
	#As with all items, this value is added on top of the default attack speed of the player (which is 4.0 by default).
	#Format for every entry is "<namespace>:<path>,<amount>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
	#Default Value: []
	#Requires Restart: Game
	attack_speed_overrides = []
	#Overrides for setting and balancing attack damage values of items.
	#As with all items, this value is added on top of the default attack strength of the player (which is 1.0 by default).
	#Format for every entry is "<namespace>:<path>,<amount>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
	#Default Value: []
	#Requires Restart: Game
	attack_damage_overrides = []
	#Overrides for setting and balancing attack reach values of items.
	#Takes precedence over any changes made by "additional_attack_reach" option.
	#As with all items, this value is added on top of the default attack reach of the player (which is 3.0 by default, and has a hard cap at 6.0).
	#Format for every entry is "<namespace>:<path>,<amount>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
	#Default Value: []
	#Requires Restart: Game
	entity_interaction_range_overrides = []
