#Range: 0.0 ~ 1.0
fruitsGrowChance = 0.1
#Range: 0.0 ~ 1.0
fruitsDropChance = 0.1
#Range: 0.0 ~ 1.0
flowerDecayChance = 0.1
#Range: 0.0 ~ 1.0
peachGrowChance = 0.1
#Range: 0.0 ~ 1.0
peachFruitChance = 0.3
#Range: 0.0 ~ 1.0
peachDecayChance = 0.1
#Range: 0 ~ 64
rageEffectRange = 24
#Range: 0 ~ 64
healEffectRange = 6
#Range: 0 ~ 64
alienatingEffectRange = 12
